apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: d1

spec:
  selector:
    matchLabels:
      label-name: task1
  replicas: 5
  template:
    metadata:
      name: pod1
      labels:
        label-name: task1

    spec:
      containers:
        - image: mariamgaber123/mariam_gaber_2023040247
          name: c1
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
        - image: mariamgaber123/mariam_gaber_2023040247
          name: c2
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"   