on:
  push:
    branches:
      - master 






jobs:
   build:
      runs-on: ubuntu-latest
      
         
      steps:
         - name: 'Testing Github action'
           run: pwd

         - name: 'Testing Printing'
           run: echo hello 

         - uses: actions/checkout@3

         - name: 'listing files'
           run: ls -a

           