on:
  push:
    branches:
      - master 






jobs:
   build:
      runs-on: ubuntu-latest
      
         
      steps:
         - name: 'Testing Github action'
           run: pwd

         - name: 'Testing Printing'
           run: echo hello 

         - uses: actions/checkout@v3

         - name: 'listing files'
           run: ls -a

         - name: 'login secrets'
           run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}
         - name: 'build image'
           run: docker build -t ${{secrets.DOCKER_USERNAME}}/task .

         - name: 'push image'
           run : docker push ${{secrets.DOCKER_USERNAME}}/task